# CREATE DB
CREATE DATABASE swamp;

# DROP TABLES
DROP TABLE User;
DROP TABLE User_Account;
DROP TABLE Bin;
DROP TABLE Collected_Waste;
DROP TABLE User_Bin;

# CREATE TABLES
CREATE TABLE User (
	uname VARCHAR(255) NOT NULL,
	passwd VARCHAR(255) NOT NULL,
    PRIMARY KEY (uname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE User_Account (
	uname VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    pp_loc VARCHAR(255) NOT NULL,
    PRIMARY KEY (uname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE Bin (
	id int(11) NOT NULL,
	loc_x DOUBLE NOT NULL,
	loc_y DOUBLE NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE Collected_Waste (
	bin_id int(11) NOT NULL,
	user_uname VARCHAR(255) NOT NULL,
	amount DOUBLE NOT NULL,
	dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (bin_id, user_uname, dt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE User_Bin (
	user_uname VARCHAR(255) NOT NULL,
	bin_id int(11) NOT NULL,
    PRIMARY KEY (user_uname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;