# CREATE TABLES
CREATE TABLE User (
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
PRIMARY KEY (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE User_Account (
	username VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    totalRecycled DOUBLE NOT NULL,
    monthlyRecycled DOUBLE NOT NULL,
PRIMARY KEY (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE Bin (
	id int(11) NOT NULL,
	locX DOUBLE NOT NULL,
	locY DOUBLE NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE Recycled (
	binId int(11) NOT NULL,
	username VARCHAR(255) NOT NULL,
	amount DOUBLE NOT NULL,
	dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (binId, username, dt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE User_Bin (
	username VARCHAR(255) NOT NULL,
	binId int(11) NOT NULL,
	amount DOUBLE NOT NULL,
PRIMARY KEY (username, binId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;